apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: external-secrets
spec:
  goTemplate: true
  generators:
  - clusters:
      selector:
        matchLabels:
          app.o1labs.org/external-secrets-operator: enabled
  template:
    metadata:
      name: '{{.name}}-external-secrets'
      labels:
        o1labs.org/cluster: '{{.name}}'
        o1labs.org/app: external-secrets
    spec:
      project: default
      info:
      - name: "External Secrets Operator (ESO):"
        value: "Acts as proxy to a Cloud Secrets Store, enabling Kubernetes Secrets creation from secret values stored remotely"
      sources:
      - repoURL: git@github.com:o1-labs/gitops-infrastructure.git
        targetRevision: lsanabria/bootstrap
        path: "charts/external-secrets-operator"
        helm:
          releaseName: external-secrets
          # these values have top precedence
          values: |
            external-secrets:
              commonLabels:
                o1labs.org/cluster: {{.name}}
          valueFiles:
          - values.yaml
          - $otherValues/platform/{{.name}}/external-secrets/values.yaml
      - ref: otherValues
        repoURL: git@github.com:o1-labs/gitops-infrastructure.git
        targetRevision: lsanabria/bootstrap
      destination:
        server: '{{.server}}'
        namespace: external-secrets-operator
