argo-cd:
  applicationSet:
    serviceAccount:
      annotations:
        iam.gke.io/gcp-service-account: external-secrets-operator-acct@o1labs-192920.iam.gserviceaccount.com # previously configured workload identity binding
    resources:
      limits:
        cpu: 1
        memory: 1Gi
      requests:
        cpu: 100m
        memory: 128Mi

  configs:
    params:
    server.insecure: true
    server.disable.auth:

  controller:
    serviceAccount:
      annotations:
        iam.gke.io/gcp-service-account: external-secrets-operator-acct@o1labs-192920.iam.gserviceaccount.com # previously configured workload identity binding
    resources:
      limits:
        cpu: 2
        memory: 2Gi
      requests:
        cpu: 250m
        memory: 256Mi

  dex:
    serviceAccount:
      annotations:
        iam.gke.io/gcp-service-account: external-secrets-operator-acct@o1labs-192920.iam.gserviceaccount.com # previously configured workload identity binding
    resources:
      limits:
        cpu: 50m
        memory: 64Mi
      requests:
        cpu: 10m
        memory: 32Mi

  notifications:
    resources:
      limits:
        cpu: 100m
        memory: 128Mi
      requests:
        cpu: 100m
        memory: 128Mi

  redis:
    resources:
      limits:
        cpu: 200m
        memory: 128Mi
      requests:
        cpu: 100m
        memory: 64Mi

  repoServer:
    serviceAccount:
      annotations:
        iam.gke.io/gcp-service-account: external-secrets-operator-acct@o1labs-192920.iam.gserviceaccount.com # previously configured workload identity binding
    env:
    ## allowing longer checkouts for e.g., mina repo
    - name: ARGOCD_EXEC_TIMEOUT
      value: 5m
    ## Enabling helmfile deployments
    volumes:
    - emptyDir: {}
      name: helmfile-cmp-tmp
    extraContainers:
    - name: helmfile-plugin
      image: travisghansen/argo-cd-helmfile:v0.3.6
      command: [/var/run/argocd/argocd-cmp-server]
      volumeMounts:
      - mountPath: /var/run/argocd
        name: var-files
      - mountPath: /home/argocd/cmp-server/plugins
        name: plugins
      - mountPath: /tmp
        name: helmfile-cmp-tmp
    resources:
      limits:
        cpu: 50m
        memory: 128Mi
      requests:
        cpu: 10m
        memory: 64Mi

  server:
    serviceAccount:
      annotations:
        iam.gke.io/gcp-service-account: external-secrets-operator-acct@o1labs-192920.iam.gserviceaccount.com # previously configured workload identity binding
    ingress:
      enabled: false
    service:
      annotations:
        external-dns.alpha.kubernetes.io/hostname: "argo-cd.gcp.o1test.net"
      type: LoadBalancer
    resources:
      limits:
        cpu: 100m
        memory: 128Mi
      requests:
        cpu: 50m
        memory: 64Mi
