argo-cd:
  applicationSet:
    serviceAccount:
      annotations:
        iam.gke.io/gcp-service-account: external-secrets-operator-acct@o1labs-192920.iam.gserviceaccount.com # previously configured workload identity binding
    resources:
      limits:
        cpu: 1
        memory: 1Gi
      requests:
        cpu: 100m
        memory: 128Mi

  configs:
    params:
    server.insecure: true
    server.disable.auth:
    cm:
      helm.valuesFileSchemes: >-
        secrets+gpg-import, secrets+gpg-import-kubernetes, secrets+age-import, secrets+age-import-kubernetes, secrets,secrets+literal, https
  controller:
    serviceAccount:
      annotations:
        iam.gke.io/gcp-service-account: external-secrets-operator-acct@o1labs-192920.iam.gserviceaccount.com # previously configured workload identity binding
    resources:
      limits:
        cpu: 2
        memory: 2Gi
      requests:
        cpu: 250m
        memory: 256Mi

  dex:
    serviceAccount:
      annotations:
        iam.gke.io/gcp-service-account: external-secrets-operator-acct@o1labs-192920.iam.gserviceaccount.com # previously configured workload identity binding
    resources:
      limits:
        cpu: 50m
        memory: 64Mi
      requests:
        cpu: 10m
        memory: 32Mi

  notifications:
    resources:
      limits:
        cpu: 100m
        memory: 128Mi
      requests:
        cpu: 100m
        memory: 128Mi

  redis:
    resources:
      limits:
        cpu: 200m
        memory: 128Mi
      requests:
        cpu: 100m
        memory: 64Mi

  repoServer:
    serviceAccount:
      annotations:
        iam.gke.io/gcp-service-account: external-secrets-operator-acct@o1labs-192920.iam.gserviceaccount.com # previously configured workload identity binding
    env:
    ## allowing longer checkouts for e.g., mina repo
    - name: ARGOCD_EXEC_TIMEOUT
      value: 5m
    - name: HELM_PLUGINS
      value: /custom-tools/helm-plugins/
    - name: HELM_SECRETS_CURL_PATH
      value: /custom-tools/curl
    - name: HELM_SECRETS_SOPS_PATH
      value: /custom-tools/sops
    - name: HELM_SECRETS_VALS_PATH
      value: /custom-tools/vals
    - name: HELM_SECRETS_KUBECTL_PATH
      value: /custom-tools/kubectl
    - name: HELM_SECRETS_BACKEND
      value: sops
    - name: HELM_SECRETS_VALUES_ALLOW_SYMLINKS
      value: "false"
    - name: HELM_SECRETS_VALUES_ALLOW_ABSOLUTE_PATH
      value: "true"
    - name: HELM_SECRETS_VALUES_ALLOW_PATH_TRAVERSAL
      value: "false"
    - name: HELM_SECRETS_WRAPPER_ENABLED
      value: "true"
    - name: HELM_SECRETS_DECRYPT_SECRETS_IN_TMP_DIR
      value: "true"
    - name: HELM_SECRETS_HELM_PATH
      value: /usr/local/bin/helm
    ## Enabling helmfile deployments
    volumes:
    - emptyDir: {}
      name: helmfile-cmp-tmp
    - name: custom-tools
      emptyDir: {}
    volumeMounts:
    - mountPath: /custom-tools
      name: custom-tools
    - mountPath: /usr/local/sbin/helm
      subPath: helm
      name: custom-tools
    initContainers:
    - name: download-tools
      image: alpine:latest
      imagePullPolicy: IfNotPresent
      command: [sh, -ec]
      env:
      - name: HELM_SECRETS_VERSION
        value: "4.5.1"
      - name: KUBECTL_VERSION
        value: "1.26.1"
      - name: VALS_VERSION
        value: "0.24.0"
      - name: SOPS_VERSION
        value: "3.8.1"
      args:
      - |
        mkdir -p /custom-tools/helm-plugins
        wget -qO- https://github.com/jkroepke/helm-secrets/releases/download/v${HELM_SECRETS_VERSION}/helm-secrets.tar.gz | tar -C /custom-tools/helm-plugins -xzf-;

        wget -qO /custom-tools/curl https://github.com/moparisthebest/static-curl/releases/latest/download/curl-amd64
        wget -qO /custom-tools/sops https://github.com/getsops/sops/releases/download/v${SOPS_VERSION}/sops-v${SOPS_VERSION}.linux.amd64
        wget -qO /custom-tools/kubectl https://dl.k8s.io/release/v${KUBECTL_VERSION}/bin/linux/amd64/kubectl

        wget -qO- https://github.com/helmfile/vals/releases/download/v${VALS_VERSION}/vals_${VALS_VERSION}_linux_amd64.tar.gz | tar -xzf- -C /custom-tools/ vals;

        cp /custom-tools/helm-plugins/helm-secrets/scripts/wrapper/helm.sh /custom-tools/helm

        chmod +x /custom-tools/*
      volumeMounts:
      - mountPath: /custom-tools
        name: custom-tools
    extraContainers:
    - name: helmfile-plugin
      image: travisghansen/argo-cd-helmfile:v0.3.8
      command: [/var/run/argocd/argocd-cmp-server]
      volumeMounts:
      - mountPath: /var/run/argocd
        name: var-files
      - mountPath: /home/argocd/cmp-server/plugins
        name: plugins
      - mountPath: /tmp
        name: helmfile-cmp-tmp
    resources:
      limits:
        cpu: 500m
        memory: 1024Mi
      requests:
        cpu: 10m
        memory: 64Mi

  server:
    serviceAccount:
      annotations:
        iam.gke.io/gcp-service-account: external-secrets-operator-acct@o1labs-192920.iam.gserviceaccount.com # previously configured workload identity binding
    ingress:
      enabled: false
    service:
      annotations:
        external-dns.alpha.kubernetes.io/hostname: "argo-cd.gcp.o1test.net"
      type: LoadBalancer
    resources:
      limits:
        cpu: 100m
        memory: 128Mi
      requests:
        cpu: 50m
        memory: 64Mi
